/**
 * @fileoverview gRPC-Web generated client stub for carapace_command
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.4.2
// 	protoc              v3.12.4
// source: carapace_command.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');

const proto = {};
proto.carapace_command = require('./carapace_command_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.carapace_command.CarapaceCommandClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.carapace_command.CarapaceCommandPromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.carapace_command.CommandRequest,
 *   !proto.carapace_command.CommandResponse>}
 */
const methodDescriptor_CarapaceCommand_SendCommand = new grpc.web.MethodDescriptor(
  '/carapace_command.CarapaceCommand/SendCommand',
  grpc.web.MethodType.UNARY,
  proto.carapace_command.CommandRequest,
  proto.carapace_command.CommandResponse,
  /**
   * @param {!proto.carapace_command.CommandRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.carapace_command.CommandResponse.deserializeBinary
);


/**
 * @param {!proto.carapace_command.CommandRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.carapace_command.CommandResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.carapace_command.CommandResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.carapace_command.CarapaceCommandClient.prototype.sendCommand =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/carapace_command.CarapaceCommand/SendCommand',
      request,
      metadata || {},
      methodDescriptor_CarapaceCommand_SendCommand,
      callback);
};


/**
 * @param {!proto.carapace_command.CommandRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.carapace_command.CommandResponse>}
 *     Promise that resolves to the response
 */
proto.carapace_command.CarapaceCommandPromiseClient.prototype.sendCommand =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/carapace_command.CarapaceCommand/SendCommand',
      request,
      metadata || {},
      methodDescriptor_CarapaceCommand_SendCommand);
};


module.exports = proto.carapace_command;

